-- 1. Remover tabelas se existirem para garantir schema limpo
DROP TABLE IF EXISTS public.boloes;
DROP TABLE IF EXISTS public.produtos;
DROP TYPE IF EXISTS public.bolao_status;

-- 2. Criar tipo ENUM para status
CREATE TYPE public.bolao_status AS ENUM ('disponivel', 'finalizado', 'cancelado');

-- 3. Criar tabela de produtos (loterias)
CREATE TABLE public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nome TEXT NOT NULL,
    slug TEXT UNIQUE, -- Identificador opcional
    cor TEXT NOT NULL,
    cor_destaque TEXT,
    icone TEXT NOT NULL DEFAULT 'Clover',
    dias_sorteio INTEGER[] NOT NULL DEFAULT '{1,2,3,4,5,6}',
    min_dezenas INTEGER NOT NULL DEFAULT 6,
    max_dezenas INTEGER NOT NULL DEFAULT 15,
    horario_fechamento TEXT NOT NULL DEFAULT '19:00',
    ativo BOOLEAN DEFAULT TRUE,
    empresa_id UUID
);

-- 4. Criar tabela de bolões
CREATE TABLE public.boloes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT REFERENCES public.produtos(id) ON DELETE CASCADE,
    concurso TEXT NOT NULL,
    data_sorteio DATE NOT NULL,
    qtd_jogos INTEGER NOT NULL DEFAULT 1,
    dezenas INTEGER NOT NULL,
    valor_cota_base DECIMAL(10, 2) NOT NULL,
    taxa_administrativa DECIMAL(10, 2) NOT NULL DEFAULT 35.00,
    qtd_cotas INTEGER NOT NULL,
    preco_venda_cota DECIMAL(10, 2) NOT NULL,
    cotas_vendidas INTEGER NOT NULL DEFAULT 0,
    status public.bolao_status DEFAULT 'disponivel',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Criar tabela de cotas individuais
CREATE TABLE public.cotas_boloes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bolao_id BIGINT REFERENCES public.boloes(id) ON DELETE CASCADE,
    uid TEXT NOT NULL, -- Identificador amigável (ex: KT-9281)
    status TEXT NOT NULL DEFAULT 'disponivel', -- disponivel, vendida, bloqueada
    data_venda TIMESTAMP WITH TIME ZONE,
    valor_venda DECIMAL(10, 2),
    forma_pagamento TEXT, -- dinheiro, pix, cartao
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Índices para performance
CREATE INDEX idx_boloes_produto_id ON public.boloes(produto_id);
CREATE INDEX idx_boloes_status ON public.boloes(status);
CREATE INDEX idx_cotas_bolao_id ON public.cotas_boloes(bolao_id);

-- 7. Habilitar RLS
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boloes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cotas_boloes ENABLE ROW LEVEL SECURITY;

-- Políticas básicas
CREATE POLICY "Permitir tudo produtos" ON public.produtos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir tudo boloes" ON public.boloes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir tudo cotas" ON public.cotas_boloes FOR ALL USING (true) WITH CHECK (true);
