-- Criação da tabela de cotas individuais para os bolões
CREATE TABLE IF NOT EXISTS public.cotas_boloes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid TEXT NOT NULL UNIQUE, -- ID amigável ex: MX-1234
    bolao_id BIGINT REFERENCES public.boloes(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'disponivel', -- disponivel, vendida
    data_venda TIMESTAMP WITH TIME ZONE,
    venda_id BIGINT, -- Link opcional para a tabela de vendas se existir
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Índices para busca rápida
CREATE INDEX idx_cotas_bolao_id ON public.cotas_boloes(bolao_id);
CREATE INDEX idx_cotas_status ON public.cotas_boloes(status);
CREATE INDEX idx_cotas_uid ON public.cotas_boloes(uid);

-- Habilitar RLS
ALTER TABLE public.cotas_boloes ENABLE ROW LEVEL SECURITY;

-- Política básica para testes
CREATE POLICY "Permitir tudo cotas_boloes" ON public.cotas_boloes FOR ALL USING (true) WITH CHECK (true);
