-- Create produtos table
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nome TEXT NOT NULL,
    slug TEXT, -- Identificador da loteria oficial
    cor TEXT NOT NULL,
    cor_destaque TEXT,
    icone TEXT NOT NULL,
    dias_sorteio INTEGER[] NOT NULL,
    min_dezenas INTEGER NOT NULL DEFAULT 6,
    max_dezenas INTEGER NOT NULL DEFAULT 15,
    horario_fechamento TEXT NOT NULL DEFAULT '19:00',
    ativo BOOLEAN DEFAULT TRUE,
    empresa_id UUID
);

-- Enable RLS
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Produtos visíveis para usuários autenticados" 
ON public.produtos FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Apenas administradores podem gerenciar produtos" 
ON public.produtos FOR ALL 
TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.usuarios 
    WHERE id = auth.uid() AND role = 'admin'
  )
) 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.usuarios 
    WHERE id = auth.uid() AND role = 'admin'
  )
);
