-- Migration: Create terminais table (Corrigida)
-- Description: Tabela para cadastro formal de terminais TFL e atualização de vínculos.

-- Garantir que não existam conflitos de tipo se a tabela foi criada incorretamente antes
DROP TABLE IF EXISTS terminais CASCADE;

-- Enum para status do terminal
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'terminal_status') THEN
        CREATE TYPE terminal_status AS ENUM ('ativo', 'manutencao', 'inativo');
    END IF;
END $$;

-- Tabela de Terminais
CREATE TABLE terminais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT UNIQUE NOT NULL,
    descricao TEXT,
    modelo TEXT,
    status terminal_status DEFAULT 'ativo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Adicionar referência na tabela caixa_sessoes
-- Garantir que a coluna tenha o tipo BIGINT compatível com a PK de 'terminais'
ALTER TABLE caixa_sessoes 
ADD COLUMN IF NOT EXISTS terminal_id_ref BIGINT REFERENCES terminais(id);

-- RLS para terminais
ALTER TABLE terminais ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Todos os usuários autenticados podem ver terminais" 
ON terminais FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Apenas gestores podem modificar terminais" 
ON terminais FOR ALL 
TO authenticated 
USING (true);
