-- Migration: Create loja_produtos (Catálogo por Filial)
-- Data: 2026-02-12
-- Objetivo: Permitir que cada filial (empresa) tenha sua própria lista de produtos (loterias) habilitados.

-- 1. Criar tabela de ligação (Pivot)
CREATE TABLE IF NOT EXISTS public.loja_produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loja_id UUID NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    produto_id BIGINT NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
    ativo BOOLEAN DEFAULT TRUE,
    config JSONB DEFAULT '{}'::jsonb, -- Para customizações futuras (ex: horário fechamento específico)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    UNIQUE(loja_id, produto_id)
);

-- 2. Índices
CREATE INDEX IF NOT EXISTS idx_loja_produtos_loja ON public.loja_produtos(loja_id);
CREATE INDEX IF NOT EXISTS idx_loja_produtos_produto ON public.loja_produtos(produto_id);

-- 3. RLS
ALTER TABLE public.loja_produtos ENABLE ROW LEVEL SECURITY;

-- Leitura: Todos autenticados podem ver
CREATE POLICY "Todos podem ver loja_produtos" ON public.loja_produtos
    FOR SELECT
    TO authenticated
    USING (true);

-- Escrita: Apenas Admins/Gerentes (ou conforme regra de negócio futura)
CREATE POLICY "Admins podem gerenciar loja_produtos" ON public.loja_produtos
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.is_master());

-- 4. SEED INICIAL (Retira o risco de "sumir tudo")
-- Para cada loja existente, criar vínculo com TODOS os produtos ativos.
INSERT INTO public.loja_produtos (loja_id, produto_id, ativo)
SELECT e.id, p.id, TRUE
FROM public.empresas e
CROSS JOIN public.produtos p
WHERE p.ativo = TRUE
ON CONFLICT (loja_id, produto_id) DO NOTHING;

-- 5. Função Trigger para Updated_at
CREATE TRIGGER update_loja_produtos_modtime
    BEFORE UPDATE ON public.loja_produtos
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();
